### ISSUE TITLE
Create main plugin file

### ISSUE THREAD

**Issue by actual-saurabh** [actual-saurabh/activity-streams#6]
Create the main plugin file to make this installer: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

It should be called `activity-streams.php`.

**Comment by parth-gohil** [comment]
Created the main file and added a doc block to it - https://github.com/actual-saurabh/activity-streams/pull/4/commits/1be1b04effbad9244c4b0f357e6c7e7564a7fe23

I still need to make documentation changes as requested in the code review.
